"""Known-version compatibility gates and one-time migration runner."""

from plotagent.compatibility.migration import (
    AtomicDirectoryPublisher,
    DirectoryPublisher,
    FaultCheckpoint,
    KnownMigration,
    KnownMigrationError,
    KnownMigrationRegistry,
    KnownMigrationRunner,
    KnownVersionMigrationRecord,
    ManagedMigrationWorkspaceProvider,
    MigrationCancelled,
    MigrationPhase,
    MigrationStatus,
    MigrationValidator,
    MigrationWorkspaceProvider,
    ProjectSnapshotter,
    SchemaCompatibilityGate,
    SemanticFingerprint,
    SQLiteProjectSnapshotter,
    read_schema_version,
)

__all__ = [
    "AtomicDirectoryPublisher",
    "DirectoryPublisher",
    "FaultCheckpoint",
    "KnownMigration",
    "KnownMigrationError",
    "KnownMigrationRegistry",
    "KnownMigrationRunner",
    "KnownVersionMigrationRecord",
    "ManagedMigrationWorkspaceProvider",
    "MigrationCancelled",
    "MigrationPhase",
    "MigrationStatus",
    "MigrationValidator",
    "MigrationWorkspaceProvider",
    "ProjectSnapshotter",
    "SQLiteProjectSnapshotter",
    "SchemaCompatibilityGate",
    "SemanticFingerprint",
    "read_schema_version",
]
