"""Agent-neutral plotting-engine contracts and backend ports."""

from .contracts import (
    AddAnnotation,
    AppliedAction,
    BindFields,
    CreatePlot,
    EngineCapability,
    EngineColumn,
    EngineDataRef,
    EngineDataView,
    EngineField,
    EngineProfile,
    ExportPlot,
    FieldBinding,
    PlotDocument,
    PlotDocumentRef,
    PlotEngineAction,
    SetAxis,
    SetChartParameter,
    SetLegend,
    SetSeriesStyle,
    SetTitle,
)
from .data import EngineDataError, ProjectEngineDataProvider
from .ports import (
    EngineArtifact,
    EngineDataProvider,
    EngineObjectRef,
    EngineReadback,
    PlotBackend,
    PlotBackendChange,
)
from .repository import PlotDocumentRepository, StoredPlotDocument, document_ref
from .runtime import PlotEngineRuntime, RuntimeResult
from .service import EngineCatalog, EngineCommandError, PlotEngineService, PlotTransition

__all__ = [
    "AddAnnotation",
    "AppliedAction",
    "BindFields",
    "CreatePlot",
    "EngineArtifact",
    "EngineCapability",
    "EngineCatalog",
    "EngineColumn",
    "EngineCommandError",
    "EngineDataProvider",
    "EngineDataError",
    "EngineDataRef",
    "EngineDataView",
    "EngineField",
    "EngineObjectRef",
    "EngineProfile",
    "EngineReadback",
    "ExportPlot",
    "FieldBinding",
    "PlotBackend",
    "PlotBackendChange",
    "PlotDocument",
    "PlotDocumentRepository",
    "PlotDocumentRef",
    "ProjectEngineDataProvider",
    "PlotEngineAction",
    "PlotEngineRuntime",
    "PlotEngineService",
    "PlotTransition",
    "RuntimeResult",
    "SetAxis",
    "SetChartParameter",
    "SetLegend",
    "SetSeriesStyle",
    "SetTitle",
    "StoredPlotDocument",
    "document_ref",
]
