"""Agent-neutral plotting-engine contracts and backend ports."""

from .contracts import (
    AddAnnotation,
    AppliedAction,
    CreatePlot,
    EngineCapability,
    EngineColumn,
    EngineDataRef,
    EngineDataView,
    EngineField,
    EngineProfile,
    ExportPlot,
    FieldBinding,
    PlotDocument,
    PlotDocumentRef,
    PlotEngineAction,
    SetAxis,
    SetChartParameter,
    SetLegend,
    SetSeriesStyle,
    SetTitle,
)
from .ports import EngineArtifact, EngineDataProvider, EngineObjectRef, EngineReadback, PlotBackend
from .repository import PlotDocumentRepository, StoredPlotDocument, document_ref
from .service import EngineCatalog, EngineCommandError, PlotEngineService, PlotTransition

__all__ = [
    "AddAnnotation",
    "AppliedAction",
    "CreatePlot",
    "EngineArtifact",
    "EngineCapability",
    "EngineCatalog",
    "EngineColumn",
    "EngineCommandError",
    "EngineDataProvider",
    "EngineDataRef",
    "EngineDataView",
    "EngineField",
    "EngineObjectRef",
    "EngineProfile",
    "EngineReadback",
    "ExportPlot",
    "FieldBinding",
    "PlotBackend",
    "PlotDocument",
    "PlotDocumentRepository",
    "PlotDocumentRef",
    "PlotEngineAction",
    "PlotEngineService",
    "PlotTransition",
    "SetAxis",
    "SetChartParameter",
    "SetLegend",
    "SetSeriesStyle",
    "SetTitle",
    "StoredPlotDocument",
    "document_ref",
]
